# Generated by Django 4.0.3 on 2022-04-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiComment',
            fields=[
                ('Multi_Comment_ID', models.IntegerField(db_column='Multi_Comment_ID', primary_key=True, serialize=False, verbose_name='Multi_Comment_ID')),
                ('Content', models.CharField(db_column='Content', max_length=255, verbose_name='Content')),
                ('CommentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='C_ID', to='template.comments')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='U_ID', to='template.users')),
            ],
            options={
                'db_table': 'MultiComment',
            },
        ),
        migrations.AlterField(
            model_name='multicomment',
            name='CommentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CID', to='template.comments'),
        ),
        migrations.AlterField(
            model_name='multicomment',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UID', to='template.users'),
        ),
    ]
