# Generated by Django 4.0.3 on 2022-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_alter_multicomment_commentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multicomment',
            name='CommentID',
        ),
        migrations.AddField(
            model_name='multicomment',
            name='Level',
            field=models.BooleanField(db_column='Level', default=0, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='multicomment',
            name='Upper_Comment_ID',
            field=models.IntegerField(db_column='Upper_Comment_ID', default=1, verbose_name='Upper_Comment_ID'),
        ),
    ]
