# Generated by Django 4.0.3 on 2022-04-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0006_remove_multicomment_commentid_multicomment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_Name',
            field=models.CharField(db_column='Course_Name', max_length=255, unique=True, verbose_name='Course_name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_name',
            field=models.CharField(db_column='User_name', max_length=255, unique=True, verbose_name='User_name'),
        ),
    ]
