# Generated by Django 4.0.3 on 2022-04-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0008_commentslikestatus_status_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentslikestatus',
            name='Status_ID',
            field=models.IntegerField(db_column='Status_ID', default=1, primary_key=True, serialize=False, verbose_name='Status_ID'),
        ),
    ]
