# Generated by Django 4.0.3 on 2022-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0009_alter_commentslikestatus_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Credit',
            field=models.IntegerField(db_column='Credit', default=3, verbose_name='Credit'),
        ),
    ]
