# Generated by Django 4.0.3 on 2022-04-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0010_courses_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Final_Score',
            field=models.FloatField(db_column='Final_Score', null=True, verbose_name='Final_Score'),
        ),
    ]
